[tool.poetry]
name = "dsc-001-001"
version = "0.1.0"
description = "Yfinance project"
authors = ["Thomas Österling <42211685+thotte@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "dsc_001_001"}]

[tool.poetry.dependencies]
python = "^3.10"
appdirs = "1.4.4"
astroid = "2.15.5"
beautifulsoup4 = "4.12.2"
black = "23.3.0"
certifi = "2023.5.7"
cfgv = "3.3.1"
charset-normalizer = "3.1.0"
click = "8.1.3"
coverage = "7.2.7"
dill = "0.3.6"
distlib = "0.3.6"
exceptiongroup = "1.1.2"
filelock = "3.12.2"
frozendict = "2.3.8"
html5lib = "1.1"
identify = "2.5.24"
idna = "3.4"
iniconfig = "2.0.0"
isort = "5.12.0"
lazy-object-proxy = "1.9.0"
lxml = "4.9.2"
mccabe = "0.7.0"
multitasking = "0.0.11"
mypy = "1.4.1"
mypy-extensions = "1.0.0"
nodeenv = "1.8.0"
numpy = "1.25.0"
packaging = "23.1"
pandas = "2.0.3"
pandas-datareader = "0.10.0"
pandas-stubs = "2.0.2.230605"
pathspec = "0.11.1"
platformdirs = "3.8.0"
pluggy = "1.2.0"
pre-commit = "3.3.3"
pylint = "2.17.4"
pytest = "7.4.0"
python-dateutil = "2.8.2"
pytz = "2023.3"
pyyaml = "6.0"
requests = "2.31.0"
six = "1.16.0"
soupsieve = "2.4.1"
tomli = "2.0.1"
tomlkit = "0.11.8"
types-pytz = "2023.3.0.0"
typing-extensions = "4.7.1"
tzdata = "2023.3"
urllib3 = "2.0.3"
virtualenv = "20.23.1"
webencodings = "0.5.1"
wrapt = "1.15.0"
yfinance = "0.2.22"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
