name: Python app

on:
  pull_request:
  push:
    branches:
      - "**"

permissions: write-all

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install pre-commit
      run: |
        pip install pre-commit
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run pre-commit
      run: pre-commit run --all-files

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          runCmd: pytest test_sample.py

      - name: Generate Report
        run: |
          pip install pytest coverage
          coverage run -m pytest
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Slack notification
        uses: tiloio/slack-webhook-action@v1.0.1
        with:
          slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_json: '{
                                "username": "{{GITHUB_ACTOR}}",
                                "text": "{{GITHUB_ACTOR}} made some notification",
                                "icon_url": "{{CUSTOM_AUTHOR_PICTURE}}",
                                "channel": "dsc-001-001",
                                "blocks": [
                                    {
                                        "type": "section",
                                        "text": {
                                            "type": "mrkdwn",
                                            "text": "someone pushed something.\n_{{CUSTOM_COMMIT_MSG}}_"
                                        }
                                    },
                                    {
                                        "type": "context",
                                        "elements": [
                                            {
                                                "type": "mrkdwn",
                                                "text": ":speech_balloon: commit <{{CUSTOM_COMMIT_URL}}|{{CUSTOM_SHORT_GITHUB_SHA}}>"
                                            }
                                        ]
                                    }
                                ]
                            }'
